language: node_js
node_js:
  - 14.15.5
cache: npm

install:
  - npm ci

script:
  - npm run build
  - npm test

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: main