name: Github Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build environment setup
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'

    - name: Build artifacts
      run: |
        npm install
        npm run build
    
    - name: Upload build artifacts
      id: deployment
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4